// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using WWL.Models.DBContexts;
using WWL.Models.Enums;

namespace WWL.Migrations
{
    [DbContext(typeof(AccountContext))]
    [Migration("20180829181643_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WWL.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("FNUsername");

                    b.Property<bool>("LoggedIn");

                    b.Property<string>("Password");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("WWL.Models.Player", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FNUsername");

                    b.Property<int?>("TeamId");

                    b.HasKey("AccountId");

                    b.HasIndex("TeamId");

                    b.ToTable("Player");
                });

            modelBuilder.Entity("WWL.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AccountId");

                    b.Property<int>("TeamType");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Team");
                });

            modelBuilder.Entity("WWL.Models.Player", b =>
                {
                    b.HasOne("WWL.Models.Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId");
                });

            modelBuilder.Entity("WWL.Models.Team", b =>
                {
                    b.HasOne("WWL.Models.Account")
                        .WithMany("Teams")
                        .HasForeignKey("AccountId");
                });
#pragma warning restore 612, 618
        }
    }
}
